"""Add source and source_id fields to Subject model

Revision ID: 2739cf766725
Revises: e567b858f91b
Create Date: 2025-12-25 17:52:34.923275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2739cf766725'
down_revision: Union[str, Sequence[str], None] = 'e567b858f91b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('subject', sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_subject_source'), 'subject', ['source'], unique=False)
    op.create_index(op.f('ix_subject_source_id'), 'subject', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subject_source_id'), table_name='subject')
    op.drop_index(op.f('ix_subject_source'), table_name='subject')
    op.drop_column('subject', 'source_id')
    op.drop_column('subject', 'source')
    # ### end Alembic commands ###
