"""change bangumi_id type from string to integer and add index

Revision ID: bbd93366421b
Revises: 2739cf766725
Create Date: 2025-12-27 19:25:49.071414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd93366421b'
down_revision: Union[str, Sequence[str], None] = '2739cf766725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bangumi_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('sign', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_bangumi_id'), 'user', ['bangumi_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_bangumi_id'), table_name='user')
    op.drop_column('user', 'sign')
    op.drop_column('user', 'bangumi_id')
    # ### end Alembic commands ###
