"""Add indexes to collection and subject tables

Revision ID: e567b858f91b
Revises: 
Create Date: 2025-12-25 00:07:52.499996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e567b858f91b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_collection_subject_id'), 'collection', ['subject_id'], unique=False)
    op.create_index(op.f('ix_collection_updated_at'), 'collection', ['updated_at'], unique=False)
    op.create_index(op.f('ix_collection_user_id'), 'collection', ['user_id'], unique=False)
    op.create_index(op.f('ix_subject_type'), 'subject', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subject_type'), table_name='subject')
    op.drop_index(op.f('ix_collection_user_id'), table_name='collection')
    op.drop_index(op.f('ix_collection_updated_at'), table_name='collection')
    op.drop_index(op.f('ix_collection_subject_id'), table_name='collection')
    # ### end Alembic commands ###
